spring:
  application:
    name: batch-spark-demo
  
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${DB_USERNAME:batch_user}
    password: ${DB_PASSWORD:batch_password}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
  
  batch:
    job:
      enabled: false # Disable auto-start
    jdbc:
      initialize-schema: always

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,batch
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.batchspark: DEBUG
    org.springframework.batch: INFO
    org.apache.spark: WARN
    oracle.jdbc: INFO
    
server:
  port: 8080

# Custom application properties
app:
  spark:
    master: local[*]
    app-name: GenericDataProcessor
  batch:
    default-chunk-size: 100
    thread-pool-size: 4