-- Create sequences
CREATE SEQUENCE FILE_CONFIG_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE COLUMN_CONFIG_SEQ START WITH 1 INCREMENT BY 1;

-- Create FILE_CONFIG table
CREATE TABLE FILE_CONFIG (
    ID NUMBER(19) PRIMARY KEY,
    CONFIG_NAME VARCHAR2(100) NOT NULL UNIQUE,
    SOURCE_FILE_PATH VARCHAR2(500) NOT NULL,
    TARGET_TABLE_NAME VARCHAR2(100) NOT NULL,
    DELIMITER VARCHAR2(10) DEFAULT ',',
    HAS_HEADER NUMBER(1) DEFAULT 1,
    CHUNK_SIZE NUMBER(10) DEFAULT 100,
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create COLUMN_CONFIG table
CREATE TABLE COLUMN_CONFIG (
    ID NUMBER(19) PRIMARY KEY,
    FILE_CONFIG_ID NUMBER(19) NOT NULL,
    SOURCE_COLUMN_NAME VARCHAR2(100) NOT NULL,
    TARGET_COLUMN_NAME VARCHAR2(100) NOT NULL,
    DATA_TYPE VARCHAR2(50) NOT NULL,
    MAX_LENGTH NUMBER(10),
    IS_NULLABLE NUMBER(1) DEFAULT 1,
    DEFAULT_VALUE VARCHAR2(255),
    COLUMN_ORDER NUMBER(10) NOT NULL,
    TRANSFORMATION_RULE VARCHAR2(100),
    VALIDATION_RULE VARCHAR2(255),
    IS_PRIMARY_KEY NUMBER(1) DEFAULT 0,
    CONSTRAINT FK_COLUMN_CONFIG_FILE FOREIGN KEY (FILE_CONFIG_ID) REFERENCES FILE_CONFIG(ID)
);

-- Create indexes
CREATE INDEX IDX_FILE_CONFIG_NAME ON FILE_CONFIG(CONFIG_NAME);
CREATE INDEX IDX_FILE_CONFIG_ACTIVE ON FILE_CONFIG(IS_ACTIVE);
CREATE INDEX IDX_COLUMN_CONFIG_FILE_ID ON COLUMN_CONFIG(FILE_CONFIG_ID);
CREATE INDEX IDX_COLUMN_CONFIG_ORDER ON COLUMN_CONFIG(COLUMN_ORDER);