-- Insert sample employee configuration
INSERT INTO FILE_CONFIG (ID, CONFIG_NAME, SOURCE_FILE_PATH, TARGET_TABLE_NAME, DELIMITER, HAS_HEADER, CHUNK_SIZE, IS_ACTIVE)
VALUES (FILE_CONFIG_SEQ.NEXTVAL, 'EMPLOYEE_DATA', 'src/main/resources/data/sample-files/employees.csv', 'EMPLOYEES', ',', 1, 100, 1);

-- Get the file config ID
DECLARE
    v_file_config_id NUMBER;
BEGIN
    SELECT ID INTO v_file_config_id FROM FILE_CONFIG WHERE CONFIG_NAME = 'EMPLOYEE_DATA';
    
    -- Insert column configurations for employee data
    INSERT INTO COLUMN_CONFIG (ID, FILE_CONFIG_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, DATA_TYPE, MAX_LENGTH, IS_NULLABLE, COLUMN_ORDER, TRANSFORMATION_RULE, VALIDATION_RULE)
    VALUES (COLUMN_CONFIG_SEQ.NEXTVAL, v_file_config_id, 'employeeId', 'EMPLOYEE_ID', 'VARCHAR2', 20, 0, 1, 'TRIM_UPPER', 'NOT_NULL');
    
    INSERT INTO COLUMN_CONFIG (ID, FILE_CONFIG_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, DATA_TYPE, MAX_LENGTH, IS_NULLABLE, COLUMN_ORDER, TRANSFORMATION_RULE, VALIDATION_RULE)
    VALUES (COLUMN_CONFIG_SEQ.NEXTVAL, v_file_config_id, 'firstName', 'FIRST_NAME', 'VARCHAR2', 50, 0, 2, 'CAPITALIZE', 'NOT_NULL');
    
    INSERT INTO COLUMN_CONFIG (ID, FILE_CONFIG_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, DATA_TYPE, MAX_LENGTH, IS_NULLABLE, COLUMN_ORDER, TRANSFORMATION_RULE, VALIDATION_RULE)
    VALUES (COLUMN_CONFIG_SEQ.NEXTVAL, v_file_config_id, 'lastName', 'LAST_NAME', 'VARCHAR2', 50, 0, 3, 'CAPITALIZE', 'NOT_NULL');
    
    INSERT INTO COLUMN_CONFIG (ID, FILE_CONFIG_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, DATA_TYPE, MAX_LENGTH, IS_NULLABLE, COLUMN_ORDER, TRANSFORMATION_RULE, VALIDATION_RULE)
    VALUES (COLUMN_CONFIG_SEQ.NEXTVAL, v_file_config_id, 'department', 'DEPARTMENT', 'VARCHAR2', 50, 0, 4, 'TRIM_UPPER', 'NOT_NULL');
    
    INSERT INTO COLUMN_CONFIG (ID, FILE_CONFIG_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, DATA_TYPE, MAX_LENGTH, IS_NULLABLE, COLUMN_ORDER, TRANSFORMATION_RULE, VALIDATION_RULE)
    VALUES (COLUMN_CONFIG_SEQ.NEXTVAL, v_file_config_id, 'salary', 'SALARY', 'NUMBER', NULL, 0, 5, NULL, 'POSITIVE_NUMBER');
    
    INSERT INTO COLUMN_CONFIG (ID, FILE_CONFIG_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, DATA_TYPE, MAX_LENGTH, IS_NULLABLE, COLUMN_ORDER, TRANSFORMATION_RULE, VALIDATION_RULE)
    VALUES (COLUMN_CONFIG_SEQ.NEXTVAL, v_file_config_id, 'hireDate', 'HIRE_DATE', 'DATE', NULL, 0, 6, 'TRIM', 'NOT_NULL');
END;
/

-- Insert sample product configuration
INSERT INTO FILE_CONFIG (ID, CONFIG_NAME, SOURCE_FILE_PATH, TARGET_TABLE_NAME, DELIMITER, HAS_HEADER, CHUNK_SIZE, IS_ACTIVE)
VALUES (FILE_CONFIG_SEQ.NEXTVAL, 'PRODUCT_DATA', 'src/main/resources/data/sample-files/products.csv', 'PRODUCTS', ',', 1, 50, 1);

DECLARE
    v_file_config_id NUMBER;
BEGIN
    SELECT ID INTO v_file_config_id FROM FILE_CONFIG WHERE CONFIG_NAME = 'PRODUCT_DATA';
    
    -- Insert column configurations for product data
    INSERT INTO COLUMN_CONFIG (ID, FILE_CONFIG_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, DATA_TYPE, MAX_LENGTH, IS_NULLABLE, COLUMN_ORDER, TRANSFORMATION_RULE, VALIDATION_RULE)
    VALUES (COLUMN_CONFIG_SEQ.NEXTVAL, v_file_config_id, 'productId', 'PRODUCT_ID', 'VARCHAR2', 20, 0, 1, 'TRIM_UPPER', 'NOT_NULL');
    
    INSERT INTO COLUMN_CONFIG (ID, FILE_CONFIG_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, DATA_TYPE, MAX_LENGTH, IS_NULLABLE, COLUMN_ORDER, TRANSFORMATION_RULE, VALIDATION_RULE)
    VALUES (COLUMN_CONFIG_SEQ.NEXTVAL, v_file_config_id, 'productName', 'PRODUCT_NAME', 'VARCHAR2', 100, 0, 2, 'TRIM', 'NOT_NULL');
    
    INSERT INTO COLUMN_CONFIG (ID, FILE_CONFIG_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, DATA_TYPE, MAX_LENGTH, IS_NULLABLE, COLUMN_ORDER, TRANSFORMATION_RULE, VALIDATION_RULE)
    VALUES (COLUMN_CONFIG_SEQ.NEXTVAL, v_file_config_id, 'category', 'CATEGORY', 'VARCHAR2', 50, 0, 3, 'TRIM_UPPER', 'NOT_NULL');
    
    INSERT INTO COLUMN_CONFIG (ID, FILE_CONFIG_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, DATA_TYPE, MAX_LENGTH, IS_NULLABLE, COLUMN_ORDER, TRANSFORMATION_RULE, VALIDATION_RULE)
    VALUES (COLUMN_CONFIG_SEQ.NEXTVAL, v_file_config_id, 'price', 'PRICE', 'NUMBER', NULL, 0, 4, NULL, 'POSITIVE_NUMBER');
    
    INSERT INTO COLUMN_CONFIG (ID, FILE_CONFIG_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, DATA_TYPE, MAX_LENGTH, IS_NULLABLE, COLUMN_ORDER, TRANSFORMATION_RULE, VALIDATION_RULE)
    VALUES (COLUMN_CONFIG_SEQ.NEXTVAL, v_file_config_id, 'quantity', 'QUANTITY', 'NUMBER', NULL, 1, 5, NULL, 'NUMERIC');
    
    INSERT INTO COLUMN_CONFIG (ID, FILE_CONFIG_ID, SOURCE_COLUMN_NAME, TARGET_COLUMN_NAME, DATA_TYPE, MAX_LENGTH, IS_NULLABLE, COLUMN_ORDER, TRANSFORMATION_RULE, VALIDATION_RULE)
    VALUES (COLUMN_CONFIG_SEQ.NEXTVAL, v_file_config_id, 'createdDate', 'CREATED_DATE', 'DATE', NULL, 1, 6, 'TRIM', NULL);
END;
/

COMMIT;